### ISSUE TITLE
found a bug in sqlquery.py file

### ISSUE THREAD

**Issue by libin0396** [thombashi/SimpleSQLite#64] opened 2019-01-19 10:36 UTC
at the line 67
`if typepy.is_not_null_string(where): `
I think it should be 
`if where:`

**Comment by thombashi** [comment] 2019-01-19 13:40
Thank you for your report.

Let me confirm the bug details and how to reproduce.
Are you mentioning the case that passing a `simplesqlite.query.Where` instance to `where` argument of `make_update` method?
In that case, generated query will not include `where` clause.
I was not considering such that case, but it may be more desirable behavior to accept `Where` instances.
Other than that, I think the method behaves properly.
Please let me know if you found any other inputs that induce errors.

**Comment by libin0396** [comment] 2019-01-20 08:57
[Here is the example in your website](https://simplesqlite.readthedocs.io/en/latest/pages/examples/update.html)
Got wrong output after updating.

**Comment by thombashi** [comment] 2019-01-20 13:58
@libin0396 
Thank you for additional information.

I had fixed the `update` problem at `SimpleSQLite 0.36.0`.
The problem was the handling of `simplesqlite.query.Where` instances as I wrote the above.

>Insert method dose not work too,used the example in your website.

I am not sure what would be a problem for this part.
Could you provide the following information to reproduce the problem?:

- `SimpleSQLite` version that you use (reproduce with the latest version?)
- Which example you are referring to (there are two insert examples)
- The output of the sample code

**Comment by libin0396** [comment] 2019-01-20 14:44
<img width="662" alt="default" src="https://user-images.githubusercontent.com/22762285/51440711-ea54a000-1d04-11e9-8788-13f234199525.png">
<img width="899" alt="2" src="https://user-images.githubusercontent.com/22762285/51440712-ea54a000-1d04-11e9-98bd-b03b5caa8b7b.png">

**Comment by thombashi** [comment] 2019-01-21 10:21
@libin0396 

Thank you for the details.

Unfortunately, I could not reproduce the problem at Ubuntu 16.04/18.04

The error might be the caused by Python caches of a `SimpleSQLite` old version.
An argument name of `insert_many` method was renamed from `record_list` to `records` at `SimpleSQLite 35.0` (the sample code also rewrote to align this change).
If cache created by `SimpleSQLite 34.0` or older still existed in your system, it may cause failure at `SimpleSQLite 35.0` or later.

Could you try the followings to avoid the error?:

- Remove the Python cache files (`.pyc`) of `SimpleSQLite` in your system if there are any
- Remove the keyword argument `records` like the below

```py
from simplesqlite import SimpleSQLite

table_name = "sample_table"
con = SimpleSQLite("sample.sqlite", "w")
con.create_table_from_data_matrix(
    table_name, ["attr_a", "attr_b", "attr_c", "attr_d", "attr_e"], [[1, 1.1, "aaa", 1, 1]]
)

con.insert(
    table_name,
    record={"attr_a": 4, "attr_b": 4.4, "attr_c": "ddd", "attr_d": 4.44, "attr_e": "hoge"},
)
con.insert_many(
    table_name,
    [  # remove 'records=' here
        {"attr_a": 5, "attr_b": 5.5, "attr_c": "eee", "attr_d": 5.55, "attr_e": "foo"},
        {"attr_a": 6, "attr_c": "fff"},
    ],
)

result = con.select(select="*", table_name=table_name)
for record in result.fetchall():
    print(record)
```

**Comment by libin0396** [comment] 2019-01-21 15:16
Thanks a lot for your patient reply.
Checked version in the pip list , it was 0.34.0, after updating to 0.36.0, it works finally.

**Comment by thombashi** [comment] 2019-01-22 13:32
Thank you for your confirmation.
I'll close the issue then.

**Closed by thombashi** 2019-01-22 13:32 UTC
Labels: bug
